import type { StandData } from './types'

export const STANDS_DATA: StandData[] = [
  {
    id: 'STD-001',
    title: 'Stand Innovación Educativa',
    meta: 'Experiencia de realidad aumentada para recorridos virtuales del campus universitario con overlays informativos interactivos.',
    status: 'published',
    proyecto: 'AR Campus Experience',
    sala: 'Sala 1',
    createdAt: '15/01/2025',
    updatedAt: '12/03/2025',
    author: 'Dra. María González',
  },
  {
    id: 'STD-002',
    title: 'Stand Tecnología Blockchain',
    meta: 'Sistema de trazabilidad descentralizado para cadenas de suministro con smart contracts y verificación en tiempo real.',
    status: 'pending',
    proyecto: 'Blockchain Tracker',
    sala: 'Sala 2',
    createdAt: '01/02/2025',
    updatedAt: '10/03/2025',
    author: 'Ing. Carlos Ramírez',
  },
  {
    id: 'STD-003',
    title: 'Stand Cloud y Colaboración',
    meta: 'Entorno de colaboración en tiempo real con edición simultánea, video conferencias y gestión documental integrada.',
    status: 'published',
    proyecto: 'Collab Platform',
    sala: 'Sala 3',
    createdAt: '20/11/2024',
    updatedAt: '14/03/2025',
    author: 'Lic. Ana Martínez',
  },
  {
    id: 'STD-004',
    title: 'Stand IoT y Automatización',
    meta: 'Suite de automatización del hogar con control de dispositivos IoT, dashboards personalizados y API de integración abierta.',
    status: 'published',
    proyecto: 'IoT Home Automation Suite',
    sala: 'Sala 4',
    createdAt: '05/09/2024',
    updatedAt: '28/02/2025',
    author: 'Ing. Pedro Sánchez',
  },
  {
    id: 'STD-005',
    title: 'Stand Ciberseguridad',
    meta: 'Plataforma de inteligencia contra amenazas cibernéticas con análisis de malware, detección de anomalías y reports automatizados.',
    status: 'draft',
    proyecto: 'Cybersecurity Threat Intelligence',
    sala: 'Sala 5',
    createdAt: '28/01/2025',
    updatedAt: '11/03/2025',
    author: 'Ing. Jorge Herrera',
  },
  {
    id: 'STD-006',
    title: 'Stand Inteligencia Artificial',
    meta: 'Plataforma de análisis de datos educativos con inteligencia artificial para predecir rendimiento estudiantil.',
    status: 'published',
    proyecto: 'AI-Powered Analytics',
    sala: 'Sala 1',
    createdAt: '10/12/2024',
    updatedAt: '05/03/2025',
    author: 'Dra. Laura Fernández',
  },
  {
    id: 'STD-007',
    title: 'Stand Realidad Virtual',
    meta: 'Experiencia inmersiva de visitas virtuales a museos y galerías de arte con navegación espacial 3D.',
    status: 'pending',
    proyecto: 'VR Museum Experience',
    sala: 'Sala 2',
    createdAt: '01/03/2025',
    updatedAt: '15/03/2025',
    author: 'Ing. Roberto Díaz',
  },
  {
    id: 'STD-008',
    title: 'Stand Startups EduTech',
    meta: 'Zona de exhibición para startups del ecosistema educativo con demos interactivas y networking.',
    status: 'draft',
    proyecto: 'EduTech Hub',
    sala: 'Sala 6',
    createdAt: '15/03/2025',
    updatedAt: '20/03/2025',
    author: 'Lic. Carmen Torres',
  },
]

export const STAND_SALAS = [
  'Todas',
  'Sala 1',
  'Sala 2',
  'Sala 3',
  'Sala 4',
  'Sala 5',
  'Sala 6',
]

export const STAND_PROYECTOS = [
  'Todos',
  'AI-Powered Analytics',
  'Blockchain Tracker',
  'Collab Platform',
  'IoT Home Automation Suite',
  'Cybersecurity Threat Intelligence',
  'AR Campus Experience',
  'VR Museum Experience',
  'EduTech Hub',
]
