export { default as ProjectsView } from './components/ProjectsView'
export { default as ProjectCard } from './components/ProjectCard'
export { default as ProjectDetailModal } from './components/ProjectDetailModal'
export type { ProjectData, ProjectRole, ProjectStatus, ProjectTab, ProjectSearchFilters, ProjectDetailModalProps, ProjectCardProps } from './types'
export { PROJECTS_DATA, PROJECT_CATEGORIES } from './data'
